address comments

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -2,27 +2,21 @@
 
 CONFIG_PATH="$(snapctl get configuration-path)"
 
-# use fallback configuration mechanism if the configuration-path is set
+# Use fallback configuration mechanism if the configuration-path is set
 if [ -n "${CONFIG_PATH}" ]; then
-    # but always give precedence to the configuration-read plug
+    # But always give precedence to the configuration-read plug
     if snapctl is-connected configuration-read; then
-      logger -t ${SNAP_NAME} "Plug 'configuration-read' is connected"
-      exit 0
+      logger -t ${SNAP_NAME} "Plug 'configuration-read' is connected, \
+        the configuration-path parameter will be ignored"
+      exit 1
     fi
 
-    case "${CONFIG_PATH}" in
-        /root*) ;;
-        *)
-            >&2 echo "Invalid path. The path must be relative to root (starting with '/root')."
-            logger -t ${SNAP_NAME} "Invalid path. The path must be relative to root (starting with '/root')."
-            exit 1
-            ;;
-    esac
-
-    if [ ! -d "${CONFIG_PATH}" ]; then
-        >&2 echo "Error: configuration-path '${CONFIG_PATH}' does not exist."
-        logger -t ${SNAP_NAME} "Error: configuration-path '${CONFIG_PATH}' does not exist."
+    if [ ! -d "/root/${CONFIG_PATH}" ]; then
+        >&2 echo "Error: configuration-path '${CONFIG_PATH}' does not exist. \
+            The path must be relative to root (starting with '/root')"
+        logger -t ${SNAP_NAME} "Error: configuration-path '${CONFIG_PATH}' does not exist. \
+            The path must be relative to root (starting with '/root')"
         exit 1
     fi
-    $SNAP/usr/bin/register-device.sh "${CONFIG_PATH}/device.yaml"
+    $SNAP/usr/bin/register-device.sh "/root/${CONFIG_PATH}/device.yaml"
 fi
