fix(install): do not fail on install and allow force-registration

diff --git a/snap/hooks/connect-plug-configuration-read b/snap/hooks/connect-plug-configuration-read
--- a/snap/hooks/connect-plug-configuration-read
+++ b/snap/hooks/connect-plug-configuration-read
@@ -1,3 +1,6 @@
 #!/bin/sh -e
 
-$SNAP/usr/bin/register-device.sh
+if ! $SNAP/usr/bin/register-device.sh; then
+  logger -t "${SNAP}" "device registration failed in connect-plug-configuration-read"
+  logger -t "${SNAP}" "You can try again later by running: sudo snap run ${SNAP}.force-register-device"
+fi
