generate ssh keys on setup, move them to data sharing snap on connect

diff --git a/snap/hooks/connect-plug-rob-cos-common-write b/snap/hooks/connect-plug-rob-cos-common-write
--- a/snap/hooks/connect-plug-rob-cos-common-write
+++ b/snap/hooks/connect-plug-rob-cos-common-write
@@ -1,4 +1,18 @@
 #!/bin/sh -e
 
 $SNAP/bin/cos-registration-agent write-uid
-$SNAP/bin/cos-registration-agent generate-keys
+
+if [ -f $SNAP_USER_COMMON/device_private_key ]; then
+    cp $SNAP_USER_COMMON/device_private_key  $SNAP_COMMON/
+else
+    echo $SNAP_USER_COMMON
+    echo "could not find private_key, make sure setup action correctly executed"
+    exit 1
+fi
+if [ -f $SNAP_USER_COMMON/device_public_key.pub ]; then
+    cp $SNAP_USER_COMMON/device_public_key.pub  $SNAP_COMMON/
+else
+    echo $SNAP_USER_COMMON
+    echo "could not find private_key, make sure setup action correctly executed"
+    exit 1
+fi
